package com.vn.hungtq.peace.entity;

// default package
// Generated Mar 5, 2017 11:23:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AccountSetting generated by hbm2java
 */
@Entity
@Table(name = "account_setting")
public class AccountSetting implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2555393605113456116L;
	private Integer id;
	private int userId;
	private Boolean isDeliver;
	private String amazonAccessKey;
	private String amazonSecretKey;
	private String amazoneId;
	private String paypalEmail;
	private Boolean isImmediateStettlement;

	public AccountSetting() {
	}

	public AccountSetting(int userId) {
		this.userId = userId;
	}

	public AccountSetting(int userId, Boolean isDeliver,
			String amazonAccessKey, String amazonSecretKey, String amazoneId,
			String paypalEmail, Boolean isImmediateStettlement) {
		this.userId = userId;
		this.isDeliver = isDeliver;
		this.amazonAccessKey = amazonAccessKey;
		this.amazonSecretKey = amazonSecretKey;
		this.amazoneId = amazoneId;
		this.paypalEmail = paypalEmail;
		this.isImmediateStettlement = isImmediateStettlement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "is_deliver")
	public Boolean getIsDeliver() {
		return this.isDeliver;
	}

	public void setIsDeliver(Boolean isDeliver) {
		this.isDeliver = isDeliver;
	}

	@Column(name = "amazon_access_key", length = 200)
	public String getAmazonAccessKey() {
		return this.amazonAccessKey;
	}

	public void setAmazonAccessKey(String amazonAccessKey) {
		this.amazonAccessKey = amazonAccessKey;
	}

	@Column(name = "amazon_secret_key", length = 200)
	public String getAmazonSecretKey() {
		return this.amazonSecretKey;
	}

	public void setAmazonSecretKey(String amazonSecretKey) {
		this.amazonSecretKey = amazonSecretKey;
	}

	@Column(name = "amazone_id", length = 200)
	public String getAmazoneId() {
		return this.amazoneId;
	}

	public void setAmazoneId(String amazoneId) {
		this.amazoneId = amazoneId;
	}

	@Column(name = "paypal_email", length = 100)
	public String getPaypalEmail() {
		return this.paypalEmail;
	}

	public void setPaypalEmail(String paypalEmail) {
		this.paypalEmail = paypalEmail;
	}

	@Column(name = "isImmediateStettlement")
	public Boolean getIsImmediateStettlement() {
		return this.isImmediateStettlement;
	}

	public void setIsImmediateStettlement(Boolean isImmediateStettlement) {
		this.isImmediateStettlement = isImmediateStettlement;
	}

}
