package com.vn.hungtq.peace.entity;
 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AreaSettingInfo generated by hbm2java
 */
@Entity
@Table(name = "area_setting_info")
public class AreaSettingInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6919064059714945755L;
	private Integer id;
	private TimeUnitMapping timeUnitMapping;
	private String timeShipping;
	private Boolean isFree;
	private Boolean isNoShipping;
	private Boolean isAsk;
	private int userId;
	private Boolean isChoice;
	private Integer useOnArea;

	public AreaSettingInfo() {
	}

	public AreaSettingInfo(TimeUnitMapping timeUnitMapping, String timeShipping,
			int userId) {
		this.timeUnitMapping = timeUnitMapping;
		this.timeShipping = timeShipping;
		this.userId = userId;
	}

	public AreaSettingInfo(TimeUnitMapping timeUnitMapping, String timeShipping,
			Boolean isFree, Boolean isNoShipping, Boolean isAsk, int userId,
			Boolean isChoice, Integer useOnArea) {
		this.timeUnitMapping = timeUnitMapping;
		this.timeShipping = timeShipping;
		this.isFree = isFree;
		this.isNoShipping = isNoShipping;
		this.isAsk = isAsk;
		this.userId = userId;
		this.isChoice = isChoice;
		this.useOnArea = useOnArea;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "time_unit_mapping_id", nullable = false)
	public TimeUnitMapping getTimeUnitMapping() {
		return this.timeUnitMapping;
	}

	public void setTimeUnitMapping(TimeUnitMapping timeUnitMapping) {
		this.timeUnitMapping = timeUnitMapping;
	}

	@Column(name = "time_shipping", nullable = false)
	public String getTimeShipping() {
		return this.timeShipping;
	}

	public void setTimeShipping(String timeShipping) {
		this.timeShipping = timeShipping;
	}

	@Column(name = "is_free")
	public Boolean getIsFree() {
		return this.isFree;
	}

	public void setIsFree(Boolean isFree) {
		this.isFree = isFree;
	}

	@Column(name = "is_no_shipping")
	public Boolean getIsNoShipping() {
		return this.isNoShipping;
	}

	public void setIsNoShipping(Boolean isNoShipping) {
		this.isNoShipping = isNoShipping;
	}

	@Column(name = "is_ask")
	public Boolean getIsAsk() {
		return this.isAsk;
	}

	public void setIsAsk(Boolean isAsk) {
		this.isAsk = isAsk;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "is_choice")
	public Boolean getIsChoice() {
		return this.isChoice;
	}

	public void setIsChoice(Boolean isChoice) {
		this.isChoice = isChoice;
	}

	@Column(name = "use_on_area")
	public Integer getUseOnArea() {
		return this.useOnArea;
	}

	public void setUseOnArea(Integer useOnArea) {
		this.useOnArea = useOnArea;
	}

}
