package com.vn.hungtq.peace.entity;
 
// Generated Feb 24, 2017 2:12:31 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact")
public class Contact {
 
	private Integer id;
	private String email;
	private String name;
	private String phone;
	private Date createdDate;
	private String exhibitionCategory;
	private String describeContent;
	private Integer userId;

	public Contact() {
	}
	
	public Contact(String email, String name, String phone, Date createdDate,
			String exhibitionCategory, String describeContent) {
		this.email = email;
		this.name = name;
		this.phone = phone;
		this.createdDate = createdDate;
		this.exhibitionCategory = exhibitionCategory;
		this.describeContent = describeContent;
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "exhibition_category", nullable = false, length = 100)
	public String getExhibitionCategory() {
		return this.exhibitionCategory;
	}

	public void setExhibitionCategory(String exhibitionCategory) {
		this.exhibitionCategory = exhibitionCategory;
	}

	@Column(name = "describe_content", nullable = false, length = 200)
	public String getDescribeContent() {
		return this.describeContent;
	}

	public void setDescribeContent(String describeContent) {
		this.describeContent = describeContent;
	}
	
	@Column(name = "userId", nullable = false, length = 11)
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}
