package com.vn.hungtq.peace.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CountryGroup generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "country_group")
public class CountryGroup implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean isActive;

	public CountryGroup() {
	}

	public CountryGroup(String name) {
		this.name = name;
	}

	public CountryGroup(String name, Boolean isActive) {
		this.name = name;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
