package com.vn.hungtq.peace.entity;
 

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EbayShippingMethod generated by hbm2java
 */
@Entity
@Table(name = "ebay_shipping_method")
public class EbayShippingMethod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5776287390053483034L;
	private Integer id;
	private String name;
	private Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps = new HashSet<EbayAreaShippingMethodMap>(0);

	public EbayShippingMethod() {
	}

	public EbayShippingMethod(String name) {
		this.name = name;
	}

	public EbayShippingMethod(String name, Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps) {
		this.name = name;
		this.ebayAreaShippingMethodMaps = ebayAreaShippingMethodMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ebayShippingMethod")
	public Set<EbayAreaShippingMethodMap> getEbayAreaShippingMethodMaps() {
		return this.ebayAreaShippingMethodMaps;
	}

	public void setEbayAreaShippingMethodMaps(Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps) {
		this.ebayAreaShippingMethodMaps = ebayAreaShippingMethodMaps;
	}

}
