package com.vn.hungtq.peace.entity;
 

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EbayShippingArea generated by hbm2java
 */
@Entity
@Table(name = "ebay_shipping_area")
public class EbayShippingArea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2819417148949563574L;
	private Integer id;
	private String name;
	private Set<EbaySettingLayoutConfiguration> ebaySettingLayoutConfigurations = new HashSet<EbaySettingLayoutConfiguration>(0);
	private Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps = new HashSet<EbayAreaShippingMethodMap>(0);

	public EbayShippingArea() {
	}

	public EbayShippingArea(String name) {
		this.name = name;
	}

	public EbayShippingArea(String name, Set<EbaySettingLayoutConfiguration> ebaySettingLayoutConfigurations,
			Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps) {
		this.name = name;
		this.ebaySettingLayoutConfigurations = ebaySettingLayoutConfigurations;
		this.ebayAreaShippingMethodMaps = ebayAreaShippingMethodMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ebayShippingArea")
	public Set<EbaySettingLayoutConfiguration> getEbaySettingLayoutConfigurations() {
		return this.ebaySettingLayoutConfigurations;
	}

	public void setEbaySettingLayoutConfigurations(
			Set<EbaySettingLayoutConfiguration> ebaySettingLayoutConfigurations) {
		this.ebaySettingLayoutConfigurations = ebaySettingLayoutConfigurations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ebayShippingArea")
	public Set<EbayAreaShippingMethodMap> getEbayAreaShippingMethodMaps() {
		return this.ebayAreaShippingMethodMaps;
	}

	public void setEbayAreaShippingMethodMaps(Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps) {
		this.ebayAreaShippingMethodMaps = ebayAreaShippingMethodMaps;
	}

}
