package com.vn.hungtq.peace.entity; 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EbayShippingFee generated by hbm2java
 */
@Entity
@Table(name = "ebay_shipping_fee")
public class EbayShippingFee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8756830070230474909L;
	private Integer id;
	private EbayShippingArea ebayShippingAreaByFirstGroupAreaId;
	private EbayShippingArea ebayShippingAreaBySecondGroupAreaId;
	private EbayShippingArea ebayShippingAreaByThirdGroupAreaId;
	private EbayShippingArea ebayShippingAreaByFourGroupAreaId;
	private int userId;
	private int firstShippingMethodId;
	private int secondShippingMethodId;
	private int thirdShippingMethodId;
	private int fourShippingMethodId;
	private int numberOfDayToShip;

	public EbayShippingFee() {
	}

	public EbayShippingFee(EbayShippingArea ebayShippingAreaByFirstGroupAreaId,
			EbayShippingArea ebayShippingAreaBySecondGroupAreaId,
			EbayShippingArea ebayShippingAreaByThirdGroupAreaId,
			EbayShippingArea ebayShippingAreaByFourGroupAreaId, int userId,
			int firstShippingMethodId, int secondShippingMethodId,
			int thirdShippingMethodId, int fourShippingMethodId,
			int numberOfDayToShip) {
		this.ebayShippingAreaByFirstGroupAreaId = ebayShippingAreaByFirstGroupAreaId;
		this.ebayShippingAreaBySecondGroupAreaId = ebayShippingAreaBySecondGroupAreaId;
		this.ebayShippingAreaByThirdGroupAreaId = ebayShippingAreaByThirdGroupAreaId;
		this.ebayShippingAreaByFourGroupAreaId = ebayShippingAreaByFourGroupAreaId;
		this.userId = userId;
		this.firstShippingMethodId = firstShippingMethodId;
		this.secondShippingMethodId = secondShippingMethodId;
		this.thirdShippingMethodId = thirdShippingMethodId;
		this.fourShippingMethodId = fourShippingMethodId;
		this.numberOfDayToShip = numberOfDayToShip;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "first_group_area_id", nullable = false)
	public EbayShippingArea getEbayShippingAreaByFirstGroupAreaId() {
		return this.ebayShippingAreaByFirstGroupAreaId;
	}

	public void setEbayShippingAreaByFirstGroupAreaId(
			EbayShippingArea ebayShippingAreaByFirstGroupAreaId) {
		this.ebayShippingAreaByFirstGroupAreaId = ebayShippingAreaByFirstGroupAreaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "second_group_area_id", nullable = false)
	public EbayShippingArea getEbayShippingAreaBySecondGroupAreaId() {
		return this.ebayShippingAreaBySecondGroupAreaId;
	}

	public void setEbayShippingAreaBySecondGroupAreaId(
			EbayShippingArea ebayShippingAreaBySecondGroupAreaId) {
		this.ebayShippingAreaBySecondGroupAreaId = ebayShippingAreaBySecondGroupAreaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "third_group_area_id", nullable = false)
	public EbayShippingArea getEbayShippingAreaByThirdGroupAreaId() {
		return this.ebayShippingAreaByThirdGroupAreaId;
	}

	public void setEbayShippingAreaByThirdGroupAreaId(
			EbayShippingArea ebayShippingAreaByThirdGroupAreaId) {
		this.ebayShippingAreaByThirdGroupAreaId = ebayShippingAreaByThirdGroupAreaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "four_group_area_id", nullable = false)
	public EbayShippingArea getEbayShippingAreaByFourGroupAreaId() {
		return this.ebayShippingAreaByFourGroupAreaId;
	}

	public void setEbayShippingAreaByFourGroupAreaId(
			EbayShippingArea ebayShippingAreaByFourGroupAreaId) {
		this.ebayShippingAreaByFourGroupAreaId = ebayShippingAreaByFourGroupAreaId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "first_shipping_method_id", nullable = false)
	public int getFirstShippingMethodId() {
		return this.firstShippingMethodId;
	}

	public void setFirstShippingMethodId(int firstShippingMethodId) {
		this.firstShippingMethodId = firstShippingMethodId;
	}

	@Column(name = "second_shipping_method_id", nullable = false)
	public int getSecondShippingMethodId() {
		return this.secondShippingMethodId;
	}

	public void setSecondShippingMethodId(int secondShippingMethodId) {
		this.secondShippingMethodId = secondShippingMethodId;
	}

	@Column(name = "third_shipping_method_id", nullable = false)
	public int getThirdShippingMethodId() {
		return this.thirdShippingMethodId;
	}

	public void setThirdShippingMethodId(int thirdShippingMethodId) {
		this.thirdShippingMethodId = thirdShippingMethodId;
	}

	@Column(name = "four_shipping_method_id", nullable = false)
	public int getFourShippingMethodId() {
		return this.fourShippingMethodId;
	}

	public void setFourShippingMethodId(int fourShippingMethodId) {
		this.fourShippingMethodId = fourShippingMethodId;
	}

	@Column(name = "number_of_day_to_ship", nullable = false)
	public int getNumberOfDayToShip() {
		return this.numberOfDayToShip;
	}

	public void setNumberOfDayToShip(int numberOfDayToShip) {
		this.numberOfDayToShip = numberOfDayToShip;
	}

}
