package com.vn.hungtq.peace.entity;
 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EbayDeliveryMethod generated by hbm2java
 */
@Entity
@Table(name = "ebay_delivery_method")
public class EbayDeliveryMethod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4557439787364548676L;
	private Integer id;
	private int userId;
	private int returnWarrantyMethodId;
	private String shippingDetail;
	private int usShippingMethodId;
	private int otherAreaShippingMethodId;

	public EbayDeliveryMethod() {
	}

	public EbayDeliveryMethod(int userId, int returnWarrantyMethodId,
			String shippingDetail, int usShippingMethodId,
			int otherAreaShippingMethodId) {
		this.userId = userId;
		this.returnWarrantyMethodId = returnWarrantyMethodId;
		this.shippingDetail = shippingDetail;
		this.usShippingMethodId = usShippingMethodId;
		this.otherAreaShippingMethodId = otherAreaShippingMethodId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "return_warranty_method_id", nullable = false)
	public int getReturnWarrantyMethodId() {
		return this.returnWarrantyMethodId;
	}

	public void setReturnWarrantyMethodId(int returnWarrantyMethodId) {
		this.returnWarrantyMethodId = returnWarrantyMethodId;
	}

	@Column(name = "shipping_detail", nullable = false, length = 200)
	public String getShippingDetail() {
		return this.shippingDetail;
	}

	public void setShippingDetail(String shippingDetail) {
		this.shippingDetail = shippingDetail;
	}

	@Column(name = "us_shipping_method_id", nullable = false)
	public int getUsShippingMethodId() {
		return this.usShippingMethodId;
	}

	public void setUsShippingMethodId(int usShippingMethodId) {
		this.usShippingMethodId = usShippingMethodId;
	}

	@Column(name = "other_area_shipping_method_id", nullable = false)
	public int getOtherAreaShippingMethodId() {
		return this.otherAreaShippingMethodId;
	}

	public void setOtherAreaShippingMethodId(int otherAreaShippingMethodId) {
		this.otherAreaShippingMethodId = otherAreaShippingMethodId;
	}

}
