package com.vn.hungtq.peace.entity;
 

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.vn.hungtq.peace.entity.EbayAreaShippingMethodMap;

/**
 * EbayShippingMethod generated by hbm2java
 */
@Entity
@Table(name = "ebay_shipping_method")
public class EbayShippingMethod implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6570638018689630786L;
	private Integer id;
	private String name;
	private Boolean isUseOnSetting;
	private Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps = new HashSet<EbayAreaShippingMethodMap>(0);

	public EbayShippingMethod() {
	}

	public EbayShippingMethod(String name) {
		this.name = name;
	}

	public EbayShippingMethod(String name, Boolean isUseOnSetting,
			Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps) {
		this.name = name;
		this.isUseOnSetting = isUseOnSetting;
		this.ebayAreaShippingMethodMaps = ebayAreaShippingMethodMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_use_on_setting")
	public Boolean getIsUseOnSetting() {
		return this.isUseOnSetting;
	}

	public void setIsUseOnSetting(Boolean isUseOnSetting) {
		this.isUseOnSetting = isUseOnSetting;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ebayShippingMethod")
	public Set<EbayAreaShippingMethodMap> getEbayAreaShippingMethodMaps() {
		return this.ebayAreaShippingMethodMaps;
	}

	public void setEbayAreaShippingMethodMaps(Set<EbayAreaShippingMethodMap> ebayAreaShippingMethodMaps) {
		this.ebayAreaShippingMethodMaps = ebayAreaShippingMethodMaps;
	}
	
	@Override
	public boolean equals(Object obj) { 
		if(obj==null) return false;
		if(!(obj instanceof EbayShippingMethod)){
			return false;
		}
		
		EbayShippingMethod temp = (EbayShippingMethod)obj;
		if(temp.getId().equals(this.getId())){
			return true;
		}
		
		return false;
	}
	
	@Override
	public int hashCode() { 
		int result = 17;
        result = 31 * result + name.hashCode();
        result = 31 * result + id.hashCode();
        result = 31 * result + ebayAreaShippingMethodMaps.hashCode();
        return result; 
	}

}
