package com.vn.hungtq.peace.entity;
 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EbaySettingLayoutConfiguration generated by hbm2java
 */
@Entity
@Table(name = "ebay_setting_layout_configuration")
public class EbaySettingLayoutConfiguration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9005646814557710079L;
	private Integer id;
	private EbayShippingArea ebayShippingArea;
	private LayoutSettingArea layoutSettingArea;

	public EbaySettingLayoutConfiguration() {
	}

	public EbaySettingLayoutConfiguration(EbayShippingArea ebayShippingArea,
			LayoutSettingArea layoutSettingArea) {
		this.ebayShippingArea = ebayShippingArea;
		this.layoutSettingArea = layoutSettingArea;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_area_id", nullable = false)
	public EbayShippingArea getEbayShippingArea() {
		return this.ebayShippingArea;
	}

	public void setEbayShippingArea(EbayShippingArea ebayShippingArea) {
		this.ebayShippingArea = ebayShippingArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "setting_area_id", nullable = false)
	public LayoutSettingArea getLayoutSettingArea() {
		return this.layoutSettingArea;
	}

	public void setLayoutSettingArea(LayoutSettingArea layoutSettingArea) {
		this.layoutSettingArea = layoutSettingArea;
	}

}
