package com.vn.hungtq.peace.entity;
 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EbayAreaShippingMethodMap generated by hbm2java
 */
@Entity
@Table(name = "ebay_area_shipping_method_map")
public class EbayAreaShippingMethodMap implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1924888064383195597L;
	private Integer id;
	private EbayShippingArea ebayShippingArea;
	private EbayShippingMethod ebayShippingMethod;

	public EbayAreaShippingMethodMap() {
	}

	public EbayAreaShippingMethodMap(EbayShippingArea ebayShippingArea,
			EbayShippingMethod ebayShippingMethod) {
		this.ebayShippingArea = ebayShippingArea;
		this.ebayShippingMethod = ebayShippingMethod;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public EbayShippingArea getEbayShippingArea() {
		return this.ebayShippingArea;
	}

	public void setEbayShippingArea(EbayShippingArea ebayShippingArea) {
		this.ebayShippingArea = ebayShippingArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_method_id", nullable = false)
	public EbayShippingMethod getEbayShippingMethod() {
		return this.ebayShippingMethod;
	}

	public void setEbayShippingMethod(EbayShippingMethod ebayShippingMethod) {
		this.ebayShippingMethod = ebayShippingMethod;
	}

}
