package com.vn.hungtq.peace.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemInfomation generated by hbm2java
 */
@Entity
@Table(name = "item_infomation")
public class ItemInfomation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8895243775163962920L;
	private Integer id;
	private int userId;
	private String payment;
	private String termsOfSale;
	private String aboutUs;
	private String internationalBuyerNote;

	public ItemInfomation() {
	}

	public ItemInfomation(int userId, String payment, String termsOfSale,
			String aboutUs, String internationalBuyerNote) {
		this.userId = userId;
		this.payment = payment;
		this.termsOfSale = termsOfSale;
		this.aboutUs = aboutUs;
		this.internationalBuyerNote = internationalBuyerNote;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "payment", nullable = false, length = 500)
	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	@Column(name = "terms_of_sale", nullable = false, length = 500)
	public String getTermsOfSale() {
		return this.termsOfSale;
	}

	public void setTermsOfSale(String termsOfSale) {
		this.termsOfSale = termsOfSale;
	}

	@Column(name = "about_us", nullable = false, length = 500)
	public String getAboutUs() {
		return this.aboutUs;
	}

	public void setAboutUs(String aboutUs) {
		this.aboutUs = aboutUs;
	}

	@Column(name = "international_buyer_note", nullable = false, length = 500)
	public String getInternationalBuyerNote() {
		return this.internationalBuyerNote;
	}

	public void setInternationalBuyerNote(String internationalBuyerNote) {
		this.internationalBuyerNote = internationalBuyerNote;
	} 
}
