package com.vn.hungtq.peace.entity;
 

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LayoutSettingArea generated by hbm2java
 */
@Entity
@Table(name = "layout_setting_area")
public class LayoutSettingArea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2590592902461447905L;
	private Integer id;
	private String name;
	private Set<EbaySettingLayoutConfiguration> ebaySettingLayoutConfigurations = new HashSet<EbaySettingLayoutConfiguration>(0);

	public LayoutSettingArea() {
	}

	public LayoutSettingArea(String name) {
		this.name = name;
	}

	public LayoutSettingArea(String name, Set<EbaySettingLayoutConfiguration> ebaySettingLayoutConfigurations) {
		this.name = name;
		this.ebaySettingLayoutConfigurations = ebaySettingLayoutConfigurations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "layoutSettingArea")
	public Set<EbaySettingLayoutConfiguration> getEbaySettingLayoutConfigurations() {
		return this.ebaySettingLayoutConfigurations;
	}

	public void setEbaySettingLayoutConfigurations(
			Set<EbaySettingLayoutConfiguration> ebaySettingLayoutConfigurations) {
		this.ebaySettingLayoutConfigurations = ebaySettingLayoutConfigurations;
	}

}
