package com.vn.hungtq.peace.entity;
 

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TimeUnit generated by hbm2java
 */
@Entity
@Table(name = "time_unit")
public class TimeUnit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6731565059945890942L;
	private Integer id;
	private String name;
	private Set<TimeUnitMapping> timeUnitMappings = new HashSet<TimeUnitMapping>(0);

	public TimeUnit() {
	}

	public TimeUnit(String name) {
		this.name = name;
	}

	public TimeUnit(String name, Set<TimeUnitMapping> timeUnitMappings) {
		this.name = name;
		this.timeUnitMappings = timeUnitMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeUnit")
	public Set<TimeUnitMapping> getTimeUnitMappings() {
		return this.timeUnitMappings;
	}

	public void setTimeUnitMappings(Set<TimeUnitMapping> timeUnitMappings) {
		this.timeUnitMappings = timeUnitMappings;
	}

}
