package com.vn.hungtq.peace.entity; 

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TimeUnitMapping generated by hbm2java
 */
@Entity
@Table(name = "time_unit_mapping")
public class TimeUnitMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3165761764687258935L;
	private Integer id;
	private EbayShippingArea ebayShippingArea;
	private EbayShippingMethod ebayShippingMethod;
	private TimeUnit timeUnit;
	private String placeHolder;
	private String moneyName;
	private int useOnArea;
	private Set<AreaSettingInfo> areaSettingInfos = new HashSet<AreaSettingInfo>(0);

	public TimeUnitMapping() {
	}

	public TimeUnitMapping(EbayShippingArea ebayShippingArea,
			EbayShippingMethod ebayShippingMethod, TimeUnit timeUnit,
			String placeHolder, String moneyName, int useOnArea) {
		this.ebayShippingArea = ebayShippingArea;
		this.ebayShippingMethod = ebayShippingMethod;
		this.timeUnit = timeUnit;
		this.placeHolder = placeHolder;
		this.moneyName = moneyName;
		this.useOnArea = useOnArea;
	}

	public TimeUnitMapping(EbayShippingArea ebayShippingArea,
			EbayShippingMethod ebayShippingMethod, TimeUnit timeUnit,
			String placeHolder, String moneyName, int useOnArea,
			Set<AreaSettingInfo> areaSettingInfos) {
		this.ebayShippingArea = ebayShippingArea;
		this.ebayShippingMethod = ebayShippingMethod;
		this.timeUnit = timeUnit;
		this.placeHolder = placeHolder;
		this.moneyName = moneyName;
		this.useOnArea = useOnArea;
		this.areaSettingInfos = areaSettingInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_area_id", nullable = false)
	public EbayShippingArea getEbayShippingArea() {
		return this.ebayShippingArea;
	}

	public void setEbayShippingArea(EbayShippingArea ebayShippingArea) {
		this.ebayShippingArea = ebayShippingArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shipping_method_id", nullable = false)
	public EbayShippingMethod getEbayShippingMethod() {
		return this.ebayShippingMethod;
	}

	public void setEbayShippingMethod(EbayShippingMethod ebayShippingMethod) {
		this.ebayShippingMethod = ebayShippingMethod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "time_unit_id", nullable = false)
	public TimeUnit getTimeUnit() {
		return this.timeUnit;
	}

	public void setTimeUnit(TimeUnit timeUnit) {
		this.timeUnit = timeUnit;
	}

	@Column(name = "place_holder", nullable = false, length = 15)
	public String getPlaceHolder() {
		return this.placeHolder;
	}

	public void setPlaceHolder(String placeHolder) {
		this.placeHolder = placeHolder;
	}

	@Column(name = "money_name", nullable = false, length = 20)
	public String getMoneyName() {
		return this.moneyName;
	}

	public void setMoneyName(String moneyName) {
		this.moneyName = moneyName;
	}

	@Column(name = "use_on_area", nullable = false)
	public int getUseOnArea() {
		return this.useOnArea;
	}

	public void setUseOnArea(int useOnArea) {
		this.useOnArea = useOnArea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timeUnitMapping")
	public Set<AreaSettingInfo> getAreaSettingInfos() {
		return this.areaSettingInfos;
	}

	public void setAreaSettingInfos(Set<AreaSettingInfo> areaSettingInfos) {
		this.areaSettingInfos = areaSettingInfos;
	}

}
