package com.vn.hungtq.peace.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserTemplate generated by hbm2java
 */
@Entity
@Table(name = "user_template")
public class UserTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6849627546712423962L;
	private Integer id;
	private String title;
	private String htmlCode;
	private byte[] image;
	private int userId;

	public UserTemplate() {
	}

	public UserTemplate(String title, String htmlCode, byte[] image, int userId) {
		this.title = title;
		this.htmlCode = htmlCode;
		this.image = image;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 40)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "html_code", nullable = false, length = 65535)
	public String getHtmlCode() {
		return this.htmlCode;
	}

	public void setHtmlCode(String htmlCode) {
		this.htmlCode = htmlCode;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
